on: [push]

name: test

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rust-src, llvm-tools-preview-x86_64-unknown-linux-gnu, rustfmt-x86_64-unknown-linux-gnu, clippy-x86_64-unknown-linux-gnu, cargo-x86_64-unknown-linux-gnu

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Install QEMU
        run: sudo apt-get install qemu qemu-system-x86
      
      - name: Install Bootimage
        run: cargo install bootimage
      
      - name: Run cargo test
        run: cargo test
